### ISSUE TITLE
stuck 59%

### ISSUE THREAD

**Issue by aminemech** [Julianty123/GAntiLag#2]
only when i use your script habbo stuck in 59% if  i remove it everything goes right o
so the probleme of stucking is your script 
so how to fix that ?

**Comment by Julianty123** [comment]
I think that happens because when Habbo is loading at the same time the script is loading the gamedata api, so habbo takes more time than normal and then it rejects the connection, to solve it I have created a new thread, that same error is happening with xabbo according to a user... I'll see what I can do
